### ISSUE TITLE
Topology-aware affinity/anti-affinity policy doesn't work

### ISSUE THREAD

**Issue by changzhi1990** [containers/nri-plugins#65]
Hi, I have two nginx pods in different namespaces and I would like the pod1 to bind the NUMA0 and pod2 to bind the NUMA1. Here are the YAML files:
```
ubuntu@inspur-icx-2:~/zhi/wrk_nginx$ cat pod1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ns1
  annotations:
    resource-manager.nri.io/affinity: |+
      nginx:
        - scope:
            key: pod/namespace
            operator: In
            values:
              - ns1
          match:
            operator: AlwaysTrue
          weight: 222
      resource-manager.nri.io/anti-affinity: |+
        nginx:
          - scope:
              key: pod/namespace
              operator: NotIn
              values:
                - ns1
            match:
              operator: AlwaysTrue
            weight: 222
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

ubuntu@inspur-icx-2:~/zhi/wrk_nginx$ cat pod2.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ns2
  annotations:
    resource-manager.nri.io/affinity: |+
      nginx:
        - scope:
            key: pod/namespace
            operator: In
            values:
              - ns2
          match:
            operator: AlwaysTrue
          weight: 222
      resource-manager.nri.io/anti-affinity: |+
        nginx:
          - scope:
              key: pod/namespace
              operator: NotIn
              values:
                - ns2
            match:
              operator: AlwaysTrue
            weight: 222
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

After the pods are created successfully, check their allowed CPUs:

```
ubuntu@inspur-icx-2:~/zhi/wrk_nginx$ kubectl  exec -ti nginx -n ns2 -- cat /proc/1/status |grep Cpus_allowed_list
Cpus_allowed_list:      28-55,84-111
ubuntu@inspur-icx-2:~/zhi/wrk_nginx$ kubectl  exec -ti nginx -n ns1 -- cat /proc/1/status |grep Cpus_allowed_list
Cpus_allowed_list:      28-55,84-111
```

And the log of the NRI pod I have uploaded here:

[log.txt](https://github.com/containers/nri-plugins/files/11752384/log.txt)

**Comment by jukkar** [comment]
There were couple of issues in your yaml file:

* The `resource-manager.nri.io` should be `resource-policy.nri.io`. The documentation is still using the old resource-manager string, but this will be fixed.
* The anti-affinity settings in your examples are indented incorrectly, two spaces need to be removed from that block of settings

At least this yaml worked better, can you try again (just use nginx instead of busybox)
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: ns1
  annotations:
    resource-policy.nri.io/affinity: |+
      busybox:
        - scope:
            key: pod/namespace
            operator: In
            values:
              - ns1
          match:
            operator: AlwaysTrue
          weight: 222
    resource-policy.nri.io/anti-affinity: |+
      busybox:
        - scope:
            key: pod/namespace
            operator: NotIn
            values:
              - ns1
          match:
            operator: AlwaysTrue
          weight: 222
spec:
  containers:
  - name: busybox
    image: quay.io/crio/busybox:latest
    command:
      - sh
      - -c
      - sleep 3600
```
